services:
  postgres:
    image: postgres
    container_name: postgres_delivery_app
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: foods
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  app:
    build: .
    container_name: delivery-service-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_delivery_app:5432/foods
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
